=== nizatrum/xml_parser/src/main/java/books.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="book" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name ="direction" type="xs:string"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="countPage" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== nizatrum/xml_parser/src/main/java/books.xml
<?xml version="1.0" encoding="UTF-8" ?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book id="1">
        <title>Атлант расправил плечи</title>
        <author>Айн Ренд</author>
        <direction>Саморазвитие</direction>
        <status>Прочтено</status>
        <countPage>1408</countPage>
    </book>
    <book id="2">
        <title>Гарри Поттер</title>
        <author>Дж. К. Роулинг</author>
        <direction>Фантастика</direction>
        <status>Прочтено</status>
        <countPage>420</countPage>
    </book>
</books>
