=== nizatrum/xml_parser/src/main/java/cards.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" type="card" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="card">
        <xs:sequence>
            <xs:element name="number">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="19"/>
                        <xs:pattern value="\d{4}\s\d{4}\s\d{4}\s\d{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="paymentSystem" type="xs:string"/>
            <xs:element name ="releases" type="xs:string"/>
            <xs:element name="owner" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== nizatrum/xml_parser/src/main/java/cards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<cards xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="cards.xsd">
  <!--1 or more repetitions:-->
  <card>
    <number>1234 1234 1234 1234</number>
    <paymentSystem>MIR</paymentSystem>
    <releases>SBERBANK</releases>
    <owner>Alexander</owner>
  </card>
  <card>
    <number>3141 5322 0594 1194</number>
    <paymentSystem>VISA</paymentSystem>
    <releases>ALFA</releases>
    <owner>Alex</owner>
  </card>
  <card>
    <number>9491 9414 4341 5432</number>
    <paymentSystem>MASTERCARD</paymentSystem>
    <releases>TINKOFF</releases>
    <owner>Bob</owner>
  </card>
</cards>
