=== nizatrum/xml_parser/src/main/java/students.dtd
<!DOCTYPE students [
        <!ELEMENT students (student*)>
        <!ELEMENT student (name, phoneNumber, country, city, street)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT phoneNumber (#PCDATA)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ATTLIST student id CDATA #REQUIRED>
        ]>

=== nizatrum/xml_parser/src/main/java/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "students.dtd">-->
<!DOCTYPE students [
        <!ELEMENT students (student*)>
        <!ELEMENT student (name, phoneNumber, country, city, street)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT phoneNumber (#PCDATA)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ATTLIST student id CDATA #REQUIRED>
        ]>
<students>
    <student id="1">
        <name>Alex</name>
        <phoneNumber>12345678</phoneNumber>
        <country>The USA</country>
        <city>Denver</city>
        <street>45 Main street</street>
    </student>
    <student id="2">
        <name>Bob</name>
        <phoneNumber>87654321</phoneNumber>
        <country>Brasil</country>
        <city>Rio</city>
        <street>Main street</street>
    </student>
</students>
